# Generated by Django 5.1.7 on 2025-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_borrowing_payment_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payments_intent",
            new_name="payment_intent",
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Succeeded", "SUCCEEDED"),
                    ("Canceled", "CANCELED"),
                ],
                max_length=100,
            ),
        ),
    ]
