# Generated by Django 5.1.7 on 2025-07-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0003_delete_payment"),
        ("payments", "0003_rename_payments_intent_payment_payment_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="library.borrowing",
            ),
        ),
    ]
