# Generated by Django 5.1.7 on 2025-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
